### PR TITLE
Format code automatically using GitHub Actions

### PR DESCRIPTION
**Pull request by roby2014**
This PR should add a github action that runs on every PR review approve, formatting all the code the user added to the branch.

### CODE REVIEW

**Comment by roby2014** [comment]
eh I'm actually not sure why its the command is getting killed.. it worked on my machine ;_:

**Comment by roby2014** [comment]
eh I'm actually not sure why its the command is getting killed.. it worked on my machine ;_:

**Comment by roby2014** [comment]
The check engine format will still fail, however, the auto format action seems to be working.
IMO, check engine can be removed, since it's now useless.

**Review by RiscadoA — APPROVED** [review]

**Comment by RiscadoA** [comment]
Wait, maybe also remove the check engine format action in this PR?

**Review by RiscadoA — APPROVED** [review]

**Review by rsubtil — CHANGES_REQUESTED** [review]
(clearing approval...)

**Review by rsubtil — APPROVED** [review]

**Review by rsubtil — APPROVED** [review]

**Comment by roby2014** [comment]
Test

**Review by rsubtil — CHANGES_REQUESTED** [review]
clear

**Review by rsubtil — APPROVED** [review]

**Review by rsubtil — APPROVED** [review]

**Review by rsubtil — APPROVED** [review]

**Review by rsubtil — APPROVED** [review]
LGTM!

**Pull request merged**
