### PR TITLE
Move voxel stuff to engine

### PR DESCRIPTION
**Pull request by RiscadoA**
# Description

Move `core::gl::Vertex` and `core::gl::triangulate` to the `rendererPlugin`.
Move `parseQB` to `quadrados convert`.
Move `core::gl::Grid`, `core::gl::Palette` and `core::gl::Material` to the `voxelsPlugin`.

## Checklist

- [x] Self-review changes.
- [x] Evaluate impact on the documentation.

### CODE REVIEW

**Comment by RiscadoA** [comment]
Since these types are now in the `engine` namespace instead of `core::gl`, maybe we should change their names to something more descriptive such as `VoxelGrid`, `VoxelMaterial`, `VoxelPalette`, `VoxelVertex`. What do you think?

**Comment by luishfonseca** [comment]
> Since these types are now in the `engine` namespace instead of `core::gl`, maybe we should change their names to something more descriptive such as `VoxelGrid`, `VoxelMaterial`, `VoxelPalette`, `VoxelVertex`. What do you think?

That would be better, yes

**Review by luishfonseca — CHANGES_REQUESTED** [review]
`Grid`, `Material` and `Palette` should be prefixed with `Voxel`. For `Vertex`, I think it's ok to leave it as is.

**Comment by RiscadoA** [comment]
> `Grid`, `Material` and `Palette` should be prefixed with `Voxel`. For `Vertex`, I think it's ok to leave it as is.

The vertex type is specific for voxels - it stores a palette material index.
Prolly should also prefix it.

**Review by luishfonseca — APPROVED** [review]

**Pull request merged**
