### PR TITLE
Toggleable debug camera

### PR DESCRIPTION
**Pull request by roby2014**
# Description

Added debug camera plugin

## Checklist

- [X] Self-review changes.
- [X] Evaluate impact on the documentation.
- [X] Ensure test coverage.
- [X] Write new samples.

### CODE REVIEW

**Review by DiogoMendonc-a — APPROVED** [review]

**Comment by DiogoMendonc-a** [comment]
If we're not adding it in this pr, we should create an issue for adding controls to this camera

**Review by RiscadoA — COMMENTED** [review]
Shouldn't this plugin provide free camera movement controls too? Im not sure on how we would do that though. Should it be done directly here, or should we add a 'FreeCameraController' component in another plugin, which this one would depend on? Im leaning more towards a separate plugin, might be useful outside this plugin

**Comment by RiscadoA** [comment]
Okay we both wrote the same thing at the same time @DiogoMendonc-a xD

**Comment by DiogoMendonc-a** [comment]
Great mind think alike 😌

**Review by RiscadoA — APPROVED** [review]

**Pull request merged**
