### PR TITLE
[WIP] Shadow Mapping

### PR DESCRIPTION
**Pull request by joaopat98**
Work on #90

### CODE REVIEW

**Comment by joaopat98** [comment]
Depends on #122.

**Comment by joaopat98** [comment]
Depends on #124.

**Comment by RiscadoA** [comment]
TODO: Rename namespaces

**Comment by RiscadoA** [comment]
The renderer code has since changed a lot so this will need some refactoring before merging.

**Comment by RiscadoA** [comment]
The code has changed too much, it would be harder to rebase this than to rewrite it entirely.

**Pull request closed without merging**
